// This file was generated by Mendix Business Modeler 5.0.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package mobilenotes.proxies.microflows;

import java.util.HashMap;
import java.util.Map;
import com.mendix.core.Core;
import com.mendix.core.CoreException;
import com.mendix.systemwideinterfaces.MendixRuntimeException;
import com.mendix.systemwideinterfaces.core.IContext;

public class Microflows
{
	// These are the microflows for the MobileNotes module

	public static void mF_CreateImage(IContext context, mobilenotes.proxies.Notes _notes)
	{
		try
		{
			Map<String, Object> params = new HashMap<String, Object>();
			params.put("Notes", _notes == null ? null : _notes.getMendixObject());
			Core.execute(context, "MobileNotes.MF_CreateImage", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}

	public static void mF_CreateNote(IContext context)
	{
		try
		{
			Map<String, Object> params = new HashMap<String, Object>();
			Core.execute(context, "MobileNotes.MF_CreateNote", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
}