// This file was generated by Mendix Business Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package mobilenotes.proxies;

import com.mendix.core.Core;
import com.mendix.core.CoreException;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixIdentifier;
import com.mendix.systemwideinterfaces.core.IMendixObject;

/**
 * 
 */
public class Notes
{
	private final IMendixObject notesMendixObject;

	private final IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final String entityName = "MobileNotes.Notes";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Note("Note");

		private String metaName;

		MemberNames(String s)
		{
			metaName = s;
		}

		@Override
		public String toString()
		{
			return metaName;
		}
	}

	public Notes(IContext context)
	{
		this(context, Core.instantiate(context, "MobileNotes.Notes"));
	}

	protected Notes(IContext context, IMendixObject notesMendixObject)
	{
		if (notesMendixObject == null)
			throw new IllegalArgumentException("The given object cannot be null.");
		if (!Core.isSubClassOf("MobileNotes.Notes", notesMendixObject.getType()))
			throw new IllegalArgumentException("The given object is not a MobileNotes.Notes");

		this.notesMendixObject = notesMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Notes.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static mobilenotes.proxies.Notes initialize(IContext context, IMendixIdentifier mendixIdentifier) throws CoreException
	{
		return mobilenotes.proxies.Notes.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.getSudoContext() can be used to obtain sudo access).
	 */
	public static mobilenotes.proxies.Notes initialize(IContext context, IMendixObject mendixObject)
	{
		return new mobilenotes.proxies.Notes(context, mendixObject);
	}

	public static mobilenotes.proxies.Notes load(IContext context, IMendixIdentifier mendixIdentifier) throws CoreException
	{
		IMendixObject mendixObject = Core.retrieveId(context, mendixIdentifier);
		return mobilenotes.proxies.Notes.initialize(context, mendixObject);
	}

	public static java.util.List<mobilenotes.proxies.Notes> load(IContext context, String xpathConstraint) throws CoreException
	{
		java.util.List<mobilenotes.proxies.Notes> result = new java.util.ArrayList<mobilenotes.proxies.Notes>();
		for (IMendixObject obj : Core.retrieveXPathQuery(context, "//MobileNotes.Notes" + xpathConstraint))
			result.add(mobilenotes.proxies.Notes.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws CoreException
	{
		Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(IContext context) throws CoreException
	{
		Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(IContext context)
	{
		Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Note
	 */
	public final String getNote()
	{
		return getNote(getContext());
	}

	/**
	 * @param context
	 * @return value of Note
	 */
	public final String getNote(IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames.Note.toString());
	}

	/**
	 * Set value of Note
	 * @param note
	 */
	public final void setNote(String note)
	{
		setNote(getContext(), note);
	}

	/**
	 * Set value of Note
	 * @param context
	 * @param note
	 */
	public final void setNote(IContext context, String note)
	{
		getMendixObject().setValue(context, MemberNames.Note.toString(), note);
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final IMendixObject getMendixObject()
	{
		return notesMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final IContext getContext()
	{
		return context;
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final mobilenotes.proxies.Notes that = (mobilenotes.proxies.Notes) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static String getType()
	{
		return "MobileNotes.Notes";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Deprecated
	public String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
